### ISSUE TITLE
안드로이드 스튜디오

### ISSUE THREAD

**Issue by park-sohyeon** [park-sohyeon/Senior-Project#1]
- [ ] 2/22 안드로이드 스튜디오 강의 듣기
- [x] 2/23 수강정정 - 프로젝트 확정 짓기
- [ ] 2/23 안드로이드 스튜디오 API 
https://ddangeun.tistory.com/65 -> 공공데이터 api 가져오기

'경기도_버스도착정보 조회' 데이터 사용-> 정류소를 '광교역, 광교대학로'로 지정함.
![image](https://user-images.githubusercontent.com/64852208/155327986-47b031e4-7fdc-41e6-91a3-d44554ad8598.png)

**Comment by parkwltn** [comment]
경기도_버스도착정보 조회 **노선ID, 도착예정시간** XML Parsing
[https://github.com/zsueue/Bus](https://github.com/zsueue/Bus)
[참고: 오픈 API 데이터 가져오기(XML 문서)](https://hyeals.tistory.com/54?category=837718)
