### ISSUE TITLE
아이디어

### ISSUE THREAD

**Issue by park-sohyeon** [park-sohyeon/Senior-Project#7]
-박소현-
1. 버스기사용 쪽은 빼는 것이 좋아보임. -> 독창적이지 않음
https://gnews.gg.go.kr/news/news_detail.do?number=202103030926459962C048&s_code=C048

2. 길찾기(gps) + 빠른 버스 알림 + 전광판
-> 전광판(HW)의 역할을 키울 것 혹은 비콘. 태양열 포함시켜서 비콘 건전지 도움. 
문제점 해결: - 빠른 길을 찾기 어려운 시각장애인에게 빠른 버스 번호를 알려줌
- 정류장의 위치를 알려줌

**Comment by park-sohyeon** [comment]
https://www.hanium.or.kr/portal/notice/noticeView.do

-> 스마트 카트 알아보는 게 좋을듯
https://tattler.tistory.com/258
https://www.hanium.or.kr/portal/notice/noticeView.do

비콘 사용할 수 있음. 여기서 1,2개만 바꾸자

https://www.hanium.or.kr/portal/notice/noticeView.do

공기청정기 - https://www.hanium.or.kr/portal/notice/noticeView.do

**Comment by parkwltn** [comment]
센서
- 미세먼지
- 화재 감지
- 습도 감지

- 미세먼지 필터
- 팬: 천장 뚫어서 설치
- 열선

- 레일
자동 창문 on/off

나중에 시간 남으면 창문 앱 원격 on/off

3/12~13(일)
- [ ] 모든 졸작 스마트 창문 찾아보기
- [ ] 기술 구현 방법 찾기
- [ ] 구현할 때 필요한 장비(준비물) 정리하기

저녁 회의 후 최종!!!

3/14(월)
- [ ] 제품 시키고
- [ ] 기존 기술 찾기
- [ ] 피피티 제작 시작
